feat: Detail, Mypage 페이지 ui 구성 및 bottom tab(Tabs) 아이콘 변경
Jeremy-Kr/there-are pull request #2
Opened 2023-01-06 12:17 UTC by ddoqi

## What is this PR? :mag:

- Detail, Mypage 페이지 ui 작업을 진행하였습니다.
- Tabs의 아이콘을 추가하였습니다
- Detail 페이지의 애니메이션 기능을 추가하였습니다.
- Detail의 Progessbar 기능을 추가하였습니다.

## branch

- ui/detail -> develop

## Changes :memo:

- 확언리스트 데이터 추가 상태를 Progessbar를 통해 확인할 수 있습니다.
- Detail페이지의 애니메이션을 확인할 수 있습니다.
- Detail, Mypage의 업데이트 내역이 있습니다.

by @ddoqi

2023-01-07 03:57 UTC, Jeremy-Kr requested changes
월요일에 변경할 거 변경해서 다시 커밋 해봅시다~!

2023-01-07 03:57 UTC, Jeremy-Kr commented on navigation/Tabs.jsx
> +            return <Feather name="menu" size={24} color="black" />;
요기 컬러도 저희가 만든 테마 프로바이더를 통해서 변경 해 보는건 어떨까요?

2023-01-07 03:57 UTC, Jeremy-Kr commented on screen/Detail.jsx
> +          <Text style={{ paddingTop: 15, fontSize: 20, fontWeight: '700' }}>
....^^

2023-01-07 03:57 UTC, Jeremy-Kr commented on screen/Detail.jsx
> +              }}
....^^

2023-01-07 12:20 UTC, HongguLim commented on screen/Detail.jsx
> +          <Animatable.View
프로그레스바 라이브러리는 한번 공부해두면 앞으로도 자주 쓸수 있을것 같습니다!!

2023-01-07 12:40 UTC, hyeongkyu88 approved these changes

2023-01-07 12:40 UTC, hyeongkyu88 commented on screen/MyPage.jsx
> +`;
많은 작업 고생하셨습니다 styled-components만 알고 있었는데 emotion/native는 이번에 처음 배웠네요

2023-01-07 12:41 UTC, hyeongkyu88 approved these changes

2023-01-07 12:41 UTC, hyeongkyu88 commented on screen/MyPage.jsx
> +import styled from '@emotion/native';
많은 작업 고생하셨습니다 styled-components만 알고 있었는데 emotion/native는 이번에 처음 배웠네요

2023-01-07 15:11 UTC, JeonInguk approved these changes

2023-01-07 15:11 UTC, JeonInguk commented on navigation/Tabs.jsx
> +      />
수고 많으셨습니다!

2023-01-09 00:45 UTC, Jeremy-Kr approved these changes
LGTM

2023-01-09 00:50 UTC, merged