UI: create custom input
Jeremy-Kr/there-are pull request #4
Opened 2023-01-06 12:23 UTC by HongguLim

## What is this PR? :mag:

- CustomInput 추가

## branch

- ui/input -> develop

## Changes :memo:

- 컴포넌트로 사용할 인풋UI를 작성했습니다.
- props로 width, height, placeholder를 받아서 수정 가능하게 했습니다.

by @hyeongkyu88, @HongguLim

2023-01-06 12:34 UTC, ddoqi commented on components/Common/CustomButton.jsx
> +const CustomButton = ({ width = '100px', height = '40px' }) => {
Button에 디폴트값이 생겼군요!!

2023-01-06 12:35 UTC, ddoqi approved these changes
다음 작업때 만들어주신 input, button 재활용해볼생각에 벌써 신나요 :)

2023-01-07 04:01 UTC, Jeremy-Kr requested changes
TextInput 확인 후 다시 커밋 해 봅시다!

2023-01-07 04:01 UTC, Jeremy-Kr commented on components/Common/CustomInput.jsx
> +    ></InputContainer>
TextInput tag는 self closing이 안되나요? 가능할 것 같은데~ 한번 확인 해 봅시다!

2023-01-07 12:21 UTC, hyeongkyu88 approved these changes

2023-01-07 14:50 UTC, JeonInguk commented on components/Common/CustomButton.jsx
> +const CustomButton = ({ width = '100px', height = '40px' }) => {
디폴트 값으로 커스텀버튼을 쓰는 어느곳에서나 통일감이 느껴져 좋을 것 같습니다. 수고많으셨어요 ㅠㅜ

2023-01-07 14:56 UTC, JeonInguk approved these changes

2023-01-07 14:56 UTC, JeonInguk commented on components/Common/CustomButton.jsx
> +const CustomButton = ({ width = '100px', height = '40px' }) => {
디폴트 값설정으로 커스텀버튼을 쓰는 어느곳에서나 통일감이 느껴져 좋을 것 같습니다. 수고많으셨네요!

2023-01-08 10:59 UTC, Jeremy-Kr approved these changes
LGTM

2023-01-09 00:52 UTC, merged